/**
 * AUTH
 */
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';


/**
 * CHAT
 */

export const FECTH_MESSSAGE_SUCCESS = 'FECTH_MESSSAGE_SUCCESS';
export const FECTH_MESSSAGE_ERROR = 'FECTH_MESSSAGE_ERROR';

/**
 * ROOM
 */

export const FETCH_ROOM_SUCCESS = 'FETCH_ROOM_SUCCESS';
export const FETCH_ROOM_ERROR = 'FETCH_ROOM_ERROR';
export const REGISTER_ROOM = 'REGISTER_ROOM';

/**
 * CONTACT
 */

export const FETCH_CONTACT_SUCCESS = 'FETCH_CONTACT_SUCCESS';
export const FETCH_CONTACT_ERROR = 'FETCH_CONTACT_ERROR';
